### ISSUE TITLE
Work with cloudify-cli on MacOs

### ISSUE THREAD

**Issue by yishaihl** [cloudify-cosmo/cloudify-cli#984]
Hi,
I can't understand how to install / work with the cli on my mac os..can anyone please help me.. 
i got cloned the repo localy..how should i proceed from there? 

Thanks a lot for your help!
Yishai.

**Comment by yishaihl** [comment]
@tyacbovi any chance you can guide me with this?..thanks

**Comment by tyacbovi** [comment]
Hi @yishaihl,
Did you try to pip install the package?

**Comment by yishaihl** [comment]
as pip install test-requirements.txt ?..

**Comment by tyacbovi** [comment]
I mean:
- cd into the repo cloned directory 
- Running there 'pip install . '

**Comment by yishaihl** [comment]
For some reason i'm getting the following error:
![Screen Shot 2019-08-26 at 20 30 41](https://user-images.githubusercontent.com/39559916/63709885-80731a80-c840-11e9-8947-fa4f8949f2ba.png)
using latest cloudify container & Python 3.7.

**Comment by tyacbovi** [comment]
If you don't need a development environment of the cli, please see our guide on https://docs.cloudify.co/5.0.0/install_maintain/installation/installing-cli/#installing-on-mac-osx

**Comment by yishaihl** [comment]
This is what i tried to do initially..unfortunately when i'm pressing to download the package: 
 
![Screen Shot 2019-08-26 at 21 13 18](https://user-images.githubusercontent.com/39559916/63712430-5f152d00-c846-11e9-92b2-7e0e03f3ccbd.png)

i'm getting the main download page of Cloudify and not the package itself  (couldn't get the package anywhere else..).

**Comment by tyacbovi** [comment]
You are right the links are not easily found, will pass it along.

Here is the link:
http://repository.cloudifysource.org/cloudify/19.07.18/community-release/cloudify-cli-community-19.07.18.pkg

The full page (at the bottom) :
https://cloudify.co/getting-started/

**Comment by yishaihl** [comment]
Thanks a lot! really appreciate that.
